// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzfpvbjsxklsaisriygp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6ZnB2YmpzeGtsc2Fpc3JpeWdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMTc5MjEsImV4cCI6MjA2NDU5MzkyMX0.KbfNLQXGjPHTzSMDW4Z_cHJ_PpjRkICVlbla1pY9qb8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);